name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

Release:
  name: Release
  runs-on: ubuntu-latest
  needs: [Android, Android_SL]
  steps:
    - name: Check out git repository
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        merge-multiple: true
    - name: Generate file MD5
      run: |
        echo -e '\n### File MD5\n```' >> ./publish/changeLog.md
        cd artifacts
        md5sum *.apk >> ../publish/changeLog.md
        echo -e '```\n' >> ../publish/changeLog.md
    - name: Get package version
      run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ./publish/changeLog.md
        prerelease: false
        draft: false
        tag_name: v${{ env.PACKAGE_VERSION }}
        files: |
            artifacts/mobile-v${{ env.PACKAGE_VERSION }}.apk
